/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sumBetweenTwoInteger.kotlin.saj

import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun `sum between two integer`(){
        assertThat(sumBetweenTwoInteger(3,5))
        assertThat(sumBetweenTwoInteger(3,3))
        assertThat(sumBetweenTwoInteger(5,3))
    }
}
